### ISSUE TITLE
Problem running `sagemaker_get_execution_role()`

### ISSUE THREAD

**Issue by juliasilge** [DyfanJones/sm-docker#19]
Thank you so much for your work on this package! I am having trouble using this function on our SageMaker instance:

``` r
smdocker::sagemaker_get_execution_role()
#> Error in if (grepl(":role/", arn)) {: argument is of length zero
```

<sup>Created on 2023-03-03 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Looks like this is coming back empty:

``` r
smdocker:::sagemaker_get_caller_identity_arn()
#> character(0)
```

<sup>Created on 2023-03-03 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

In my case, `user_profile_desc[["UserSettings"]][["ExecutionRole"]])` is not `NULL` but it _is_ empty (`character(0)`) so that is what is getting returned. What I would actually want returned in my case is `domain_desc[["DefaultUserSettings"]][["ExecutionRole"]]`.

**Comment by juliasilge** [comment]
Related to `rstudio/vetiver-r#175

**Comment by DyfanJones** [comment]
Hmm interesting, can you let me know your sagemaker environment? I would like to see if i can recreate the error :)

**Comment by juliasilge** [comment]
Can you tell me a little more about what info you need for that?

**Comment by DyfanJones** [comment]
I have done a quick check on sagemaker python sdk and it looks like they have updated the method. Can you try out

```r
remotes::install_github("DyfanJones/sm-docker", ref="sagemaker_role")
```

This adds in space app check.

**Comment by juliasilge** [comment]
Yep, that branch works for me! 🙌

**Comment by DyfanJones** [comment]
I will update the unit tests and do a re-release to the cran. hoping they don't mind a quick re-release 🤞

**Comment by juliasilge** [comment]
I can also work with the GitHub version for now, so no huge rush from me.

**Comment by DyfanJones** [comment]
Closing this ticket as smdocker v0.1.2 has been released onto the cran :)
