### ISSUE TITLE
Could `sm_build()` return the image URI?

### ISSUE THREAD

**Issue by juliasilge** [DyfanJones/sm-docker#20]
To do something later with the image, I typically find I need the URI. Right now this is printed out in the logging but I can't easily get it programmatically . Would it be possible for `sm_build()` to return the image URI, instead of an invisible `NULL`?

**Comment by DyfanJones** [comment]
I am happy to include this.

**Comment by DyfanJones** [comment]
The image uri should be returned invisibly from `sm_build()`:

```r
remotes::install_github("DyfanJones/sm-docker", ref="image_uri")
```

**Comment by juliasilge** [comment]
This works great! 🙌

**Comment by DyfanJones** [comment]
Closing this ticket as smdocker v0.1.2 has been released onto the cran :)
