### ISSUE TITLE
Generating duplicate Code Build `project_name` 

### ISSUE THREAD

**Issue by juliasilge** [DyfanJones/sm-docker#25]
Hello there! 👋 I've got a problem I am running into that I would love to ask you about.

When I use `smdocker::sm_build()`, I am often running into the problem where the CodeBuild project being created has the same name as one I already made. I see errors like this:

```
## Error: ResourceAlreadyExistsException (HTTP 400). Project already exists: arn:aws:codebuild:us-east-2:350573666743:project/sagemaker-studio-d-if5drhy5daez-julia-silge-rstudio-com-8ab-dhjKrnLvCssXLNgE
```

When I drop into the internal functions like `smdocker:::build_image()`, what seems to be happening is that `smdocker:::codebuild_project_init()` is returning a `project_name` that already exists. I think it's this:

https://github.com/DyfanJones/sm-docker/blob/d58dba00e99c41ef6385a3909c4d0967c420d4b0/R/code_build.R#L39-L45

If I end up here with the same seed as another time I ended up here, then I get the same string of letters. This is a pretty common situation if you are using seeds for reproducibility in a script or R Markdown file. 

What would you think about wrapping this in something like [`withr::with_seed()`](https://withr.r-lib.org/reference/with_seed.html) and using some kind of pseudorandom seed there?

**Comment by DyfanJones** [comment]
Make sense :)

Would the withr solution resolve this or using something like uuid be more suitable? 🤔 

I wont be able to get to this unit the 13th as I am on holiday. However if you need it asap I am happy to review a PR :)

**Comment by juliasilge** [comment]
Oh, I like the idea of uuids, so something like this?

```r
metadata$project_name <- paste0(project_name_prefix, uuid::UUIDgenerate()) 
```

**Comment by DyfanJones** [comment]
Yeah that would be perfect :)
